# Generated by Django 5.1.3 on 2025-01-14 10:52

import django.db.models.deletion
import multiselectfield.db.fields
import viewsDB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение инструмента')),
                ('appeal_id', models.IntegerField(verbose_name='Номер заявки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Вышедшее из строя оборудование',
                'db_table': 'AdditionalExpenses',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('responsible_client', models.CharField(max_length=30, verbose_name='Ответственный заказчик и контактная информация')),
                ('branch', models.CharField(choices=[('yaroslavl', 'Пивзавод Ярпиво'), ('piter', 'Балтика-Санкт-Петербург'), ('tula', 'Тульский пивзавод'), ('samara', 'Балтика-Самара'), ('novosibirsk', 'Балтика-Новосибирск'), ('habarovsk', 'Балтика-Хабаровск'), ('rostow', 'Пивзавод Южная заря 1974'), ('voronej', 'Воронежский пивзавод')], default='accept', max_length=30, verbose_name='Филиал')),
                ('product_contact', models.BooleanField(verbose_name='Контакт с продуктом')),
                ('startAppeal_time', models.DateField(blank=True, null=True, verbose_name='Время подачи заявки')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Время начала изготовления')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Время окончания изготовления')),
                ('link', models.CharField(blank=True, default='/', max_length=150, null=True, verbose_name='Ссылка на заявку')),
                ('machine', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('milling', 'Фрезерный'), ('turning', 'Токарный'), ('turning_milling', 'Токарно фрезерный'), ('fdm', 'FDM принтер'), ('sla', 'SLA принтер')], max_length=110, null=True, verbose_name='Станок')),
                ('quantity_defect', models.IntegerField(blank=True, default=0, null=True, verbose_name='Брак')),
                ('ready_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('material', 'Ожидание поставки материала'), ('equipment', 'Ожидание поставки оснастки'), ('document', 'Ожидание документации')], default='accept', max_length=50, null=True, verbose_name='Ожидаем')),
                ('production_status', models.CharField(blank=True, choices=[('accept', 'Принята в работу'), ('in_work', 'В работе'), ('done', 'Готово')], max_length=100, null=True, verbose_name='Статус выполнения')),
                ('material_price', models.IntegerField(blank=True, null=True, verbose_name='Прямые затраты на сырье, Руб')),
                ('equipment_price', models.IntegerField(blank=True, null=True, verbose_name='Прямые затраты на инструмент')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'db_table': 'Appeal',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('EAM', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('material', models.CharField(blank=True, max_length=30, null=True, verbose_name='Материал')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер заготовки в мм')),
                ('AWP', models.IntegerField(blank=True, null=True, verbose_name='Средневзвешенная цена')),
                ('photo', models.ImageField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.image_directory_path, verbose_name='Ссылка на фото')),
                ('model', models.FileField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.model_directory_path, verbose_name='Ссылка на модель')),
                ('plan', models.FileField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.plan_directory_path, verbose_name='Ссылка на чертеж')),
                ('route_map', models.FileField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.route_map_directory_path, verbose_name='Ссылка на маршрутный лист')),
                ('testing_act', models.FileField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.testing_act_directory_path, verbose_name='Ссылка на акт тестирования')),
                ('solid_cam_project', models.FileField(blank=True, max_length=260, null=True, upload_to=viewsDB.models.solid_cam_project_directory_path, verbose_name='Ссылка на SolidCam проэкт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Детали',
                'db_table': 'Detail',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('designation', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Обозначение')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='кол-во')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость в рублях')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на инструмент')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка')),
                ('shape', models.CharField(blank=True, choices=[('circle ', 'круг'), ('square ', 'квадрат'), ('sheet ', 'лист'), ('hexagon ', 'шестигранник'), ('pipe ', 'труба'), ('corner ', 'уголок')], max_length=30, null=True, verbose_name='Форма материала')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина/Диаметр в мм')),
                ('long', models.IntegerField(blank=True, null=True, verbose_name='Длинна в мм')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Толщина в мм')),
                ('certificate', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ сертификата')),
                ('melting', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ плавки')),
                ('party', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ партии')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Материалы',
                'db_table': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Materials3D',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Обозначение')),
                ('printing_technology', models.CharField(blank=True, choices=[('FDM ', 'FDM'), ('SLA', 'SLA')], max_length=50, null=True, verbose_name='Технология')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество в кг/л')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на материал')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Материалы 3Д',
                'db_table': 'Materials3D',
            },
        ),
        migrations.CreateModel(
            name='TimeCosts',
            fields=[
                ('appeal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewsDB.appeal')),
                ('twt', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время работы токарного станка на 1 шт (мин)')),
                ('twd', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время простоя токарного станка на 1 шт (мин)')),
                ('mwt', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время работы фрезерного станка на 1 шт (мин)')),
                ('mwd', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время простоя фрезерного станка на 1 шт (мин)')),
                ('tmwt', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время работы токарного-фрезерного станка на 1 шт (мин)')),
                ('tmwd', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время простоя токарно-фезерного станка на 1 шт (мин)')),
                ('procurement_work', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Время потраченое на заготовительные операции (Пила, плазма, электроэррозия) 1 шт (мин)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Время работы станков',
                'db_table': 'TimeCosts',
            },
        ),
        migrations.AddField(
            model_name='appeal',
            name='EAM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewsDB.detail', verbose_name='Деталь'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='material',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewsDB.materials', verbose_name='Материал'),
        ),
    ]
